### PR TITLE
Today@NOI

### PR DESCRIPTION
**Pull request by matax87**
Implements #4 

Event's filters feature will be done, eventually, in another issue/PR.

https://user-images.githubusercontent.com/4108197/134665991-70d612dc-a2e3-48a4-a953-4efdd77aa5b8.mov

### CODE REVIEW

**Comment by matax87** [comment]
Just to give a preview

### Events
1  Events

### Event detail
2  Event detail

**Comment by matax87** [comment]
@Piiit the PR is ready. Do I need to squash the commits' history?

**Comment by Piiit** [comment]
@matax87 Could you please have a look at the failing CI pipeline logs, and fix those problems.. .thank you

**Comment by Piiit** [comment]
> Do I need to squash the commits' history?

No, I will do that when the PR is ready... that is when all CI parts pass (please let me know if the CI itself has problems)

**Comment by matax87** [comment]
The problem is that I'm using the iOS 15 sdk with Xcode 13. 
I'm going to try to fix it on monday.

**Comment by matax87** [comment]
@Piiit I changed the CI env (macOS-latest ie 10 to 11 and Xcode 13). Now the CI works as expected!

**Comment by Piiit** [comment]
@matax87 Thx, I merge this now

**Pull request merged**
