### PR TITLE
Event filters

### PR DESCRIPTION
**Pull request by matax87**
Implements event filters and updates filters bar (See #18)

### CODE REVIEW

**Comment by matax87** [comment]
Simulator Screen Shot - iPhone SE (2nd generation) - 2022-03-10 at 15 52 36
Simulator Screen Shot - iPhone SE (2nd generation) - 2022-03-10 at 15 52 40

**Comment by matax87** [comment]
@Piiit This is ready, please merge it as soon as possible; thus, @MarE1991 and @pkritzinger may review the new features afterwards.

**Comment by Piiit** [comment]
@matax87 Done :-)

**Comment by pkritzinger** [comment]
@matax87 : just a general question: when I try to open the app the system says that the beta-version has expired. is there anything I can do to access the updated version?
thanks, paul

**Comment by matax87** [comment]
> @matax87 : just a general question: when I try to open the app the system says that the beta-version has expired. is there anything I can do to access the updated version?
> thanks, paul

Please update the app to its latest version 1.0 (20220315080007) from TestFlight.

**Comment by pkritzinger** [comment]
@matax87 - no worries - looking forward to getting an update from you and @Piiit  :)

**Comment by Piiit** [comment]
We need to agree to the new agreements of the store before I am able to release. The admin is on Holiday though... Have to wait until next week. Sorry about that

**Pull request merged**
