### PR TITLE
Implements "authentication"

### PR DESCRIPTION
**Pull request by matax87**
Implements authentication with OAuth 2, with a SSO login, sign-up, logout, user info, and end session.

See https://github.com/noi-techpark/it.bz.noi.community/issues/18

### Attachments 

01-More_tab
02-More_tab_MyAccount
03-Welcome1
04-Welcome2
05-Welcome3
06-Signup
07-Login
08-Access_not_granted

### CODE REVIEW

**Comment by matax87** [comment]
@MarE1991 and @pkritzinger:

1. the my account is not the final version since we are still waiting for its final UI design.
2. @Piiit asked us to check that logged user have access to the NOI community app (via specific role `ACCESS_GRANTED`). This check must be done after the login, thus we came up with the solution of displaying a single screen with an error message where the user can just perform logout. The UI of this screen is temporary and should be take into account by @pkritzinger.

**Comment by matax87** [comment]
@Piiit as you asked I took into account both the testing machine and production authentication flow. The app has a custom Xcode configuration for using the testing machine auth flow "Release TMA", with respect to "Release" which uses the production flow. To switch configuration you must edit the "Archive the project" job. See the attached patch

```patch
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index 97133f8..f197909 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -79,7 +79,7 @@ jobs:
         run: |
           set -eo pipefail
           xcodebuild clean archive \
-            -configuration Release \
+            -configuration "Release TMA" \
             -scheme NOICommunity \
             -sdk iphoneos \
             -archivePath "$PWD/build/NOICommunity.xcarchive" \
```

**Comment by pkritzinger** [comment]
@matax87 thanks for the update. 
We've created the UI for the account and logout and are waiting for feedback from @MarE1991 and team.
I'll keep you posted.

**Comment by matax87** [comment]
@MarE1991 and @pkritzinger as usual you'll find copy and translation inside https://docs.google.com/spreadsheets/d/1Yiol3UqS-0I9q4R5HLifVMdGbTSe3ZwuYBAMPyZJthc/. The copies identifier of this feature are:

- `btn_logout`
- `label_access_not_granted`
- `access_not_granted_format`
- `label_name`
- `label_email`

We are going to need their final copy and translation.

**Comment by Piiit** [comment]
@matax87 Thanks, I merge this now to test it

**Comment by Piiit** [comment]
@matax87 Tested it and it works, great job!

@pkritzinger @MarE1991 I think we should change the text for the "not authorized" window (see `access_not_granted_format` in the translation doc; link in previous comment): Maybe add a link or email address to get in contact, and explain the circumstances a bit, which are basically "You have a valid Open Data Hub or NOI Account and you are logged in, but you miss  the permissions to access the community app. Please write to blabla@noi.bz.it to be granted" <-- not sure about the phrasing and English in general... sure you can find something better :-)

**Comment by pkritzinger** [comment]
good point @Piiit .
Could you provide a Screenshot of the current "not authorized" window so that we get a better understanding of the Layout? Thanks

**Comment by matax87** [comment]
> good point @Piiit .
> Could you provide a Screenshot of the current "not authorized" window so that we get a better understanding of the Layout? Thanks

@pkritzinger it was already included in the first post. 08-Access_not_granted

**Comment by Piiit** [comment]
Thanks matax... 

@pkritzinger You should also be able to see it after you update your testflight application...

**Comment by pkritzinger** [comment]
Hi @Piiit . Indeed, I see it. 
Anyways: would it be possible to get access to the Community App by changing the rights of our accounts or by means of a test-account? Otherwise we cannot see anything anymore. Thanks in advance

**Comment by pkritzinger** [comment]
thanks @Piiit , works perfectly fine. It would be great if you could add:
m.widmann@studiohug.com
denise@nudo-design.com

**Comment by Piiit** [comment]
@pkritzinger Done, please test

**Comment by pkritzinger** [comment]
@Piiit  - works perfectly fine - thanks

**Pull request merged**
