### PR TITLE
Some fixes and updates before MVP2

### PR DESCRIPTION
**Pull request by matax87**
1. Fixes project compilation
2. Fixes refresh event when an interval filter is active
3. Improves button style compatibility with iOS 14
4. Improves events fetching

### CODE REVIEW

**Comment by Piiit** [comment]
@matax87 This branch has conflicts, please resolve them

**Comment by matax87** [comment]
> @matax87 This branch has conflicts, please resolve them

done!

**Comment by Piiit** [comment]
@matax87 There are no changed files

**Comment by matax87** [comment]
> @matax87 There are no changed files

#96 included those patches as well and it has been merged before. Please close this PR!

**Pull request closed without merging**
